### ISSUE TITLE
On branch npm-audit-fix\nnothing to commit

### ISSUE THREAD

**Issue by moltar** [miyajan/npm-audit-pr#12]
New error:

```
Run miyajan/npm-audit-pr@v1.0.2
##[error]Error: git commit failed: {"stdout":"On branch npm-audit-fix\nnothing to commit, working tree clean","stderr":"","exitCode":1}
```

**Comment by miyajan** [comment]
@moltar 
Sorry, I can't reproduce the error.
Could you tell me the results of `npm audit fix` on the repository?

**Comment by moltar** [comment]
```
❯ npm audit fix
up to date in 5.624s

52 packages are looking for funding
  run `npm fund` for details

fixed 0 of 1 vulnerability in 1221 scanned packages
  1 vulnerability required manual review and could not be updated

❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by miyajan** [comment]
@moltar 
I got it. The `npm audit fix --force` is needed to install semver-major updates.
I have fixed this bug in `v1.0.3`.

**Comment by moltar** [comment]
Thanks!

**Comment by moltar** [comment]
Still getting the same error:

```
Run miyajan/npm-audit-pr@v1.0.3
  with:
    token: ***
    head-branch: npm-audit-fix
##[error]Error: git commit failed: {"stdout":"On branch npm-audit-fix\nnothing to commit, working tree clean","stderr":"","exitCode":1}
```

**Comment by miyajan** [comment]
@moltar 
It seems that `npm audit` found vulnerabilities but `npm audit fix` couldn't fix the vulnerabilities automatically. In that case, I think the job failure is the expected behavior, but the error message is not good.

I will fix the error message to manually fix the dependencies.

**Comment by moltar** [comment]
I don't think this is a good behavior. Every time this fails, I get a failed alert from GitHub Actions. I think failures should be something very serious.

I think maybe instead of failing it can create an issue stating that it could not upgrade something.
